server:
  port: 8082

spring:
  application:
    name: income-egress
  data:
    mongodb:
      uri: mongodb://localhost:27017/ingreso-egreso

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka